org.gradle.jvmargs=-Xmx4G
jvm=25
minecraft_version=26.2
neoForm_version=26.2-2
# NeoForge Properties
neoforge_version=26.2.0.63
# Fabric Properties
fabric_loader_version=0.19.3

# Mod Properties
mod_version=1.0.8
maven_group=io.github.flemmli97
mod_id=villagertrades
mod_author=flemmli97

# Dependencies
fabric_api_version=0.158.0+26.2
fabric_permissions_api=0.7.0
lingua_bib=26.1.2-1.0.6
# Not updated
ftb_ranks=2100.1.0

# Curse properties
curseforge_versions=26.2, Java 25, server
curseforge_page=https://www.curseforge.com/minecraft/mc-mods/villagertradeedit
curseforge_id=953996
curseforge_dep_fabric=fabric-api
curseforge_dep_neoforge=
modrinth_versions=26.2, server
modrinth_page=https://modrinth.com/mod/villagertradesedit
modrinth_id=rphz5Ci4
modrinth_dep_fabric=fabric-api
modrinth_dep_neoforge=

# Other
project_name=VillagerTrades
full_changelog=https://github.com/Flemmli97/VillagerTrades/blob/26.2/Changelog.md
discord_role=1188833162252525619
