plugins {
    id 'io.github.flemmli97.multiloader.platform-common'
}

dependencies {
    commonDependency("dev.ftb.mods:ftb-ranks-neoforge:${rootProject.ftb_ranks}") {
        transitive = false
    }
    compileOnly("io.github.flemmli97:lingua_bib:${lingua_bib}-common")
}

sourceSets.main.resources {
    srcDir "src/generated/resources"
}