modLoader="javafml"
loaderVersion="[${loader_version},)"
license="All rights reserved"
issueTrackerURL=""
[[mixins]]
config = "villagertrades.mixins.json"
[[mods]]
modId="villagertrades"
version="${version}"
displayName="Villager Trades"
displayURL="${homepage}"
logoFile="icon.png"
authors="Flemmli97"
description='''Server sided utility mod to edit villager trades'''
[[dependencies.villagertrades]]
modId="minecraft"
mandatory=true
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.villagertrades]]
modId="neoforge"
mandatory=true
versionRange="[${forge_version},)"
ordering="NONE"
side="BOTH"
