modLoader="javafml"
loaderVersion="[${loader_version},)"
license="MIT"
issueTrackerURL="https://github.com/Flemmli97/VillagerTrades/issues"
[[mixins]]
config = "villagertrades.mixins.json"
[[mods]]
modId="villagertrades"
version="${version}"
displayName="Villager Trades"
displayURL="${homepage}"
logoFile="icon.png"
authors="Flemmli97"
description='''Server sided utility mod to edit villager trades'''
[[dependencies.villagertrades]]
modId="minecraft"
type="required"
versionRange="[${mcversion},)"
ordering="NONE"
side="BOTH"
[[dependencies.villagertrades]]
modId="neoforge"
type="required"
versionRange = "[${neoforge_version},)"
ordering="NONE"
side="BOTH"
