plugins {
    id 'com.matthewprenger.cursegradle' version '1.4.0'
    id 'com.modrinth.minotaur' version '2.+'
    id 'io.github.flemmli97.multiloader.platform-neoforge'
}

neoForge {
    runs {
        var common = project(":common")
        data {
            data()
            programArguments.addAll "--all", "--mod", "villagertrades"
            programArguments.addAll "--output", common.file("src/generated/resources").absolutePath
        }
        client {
            jvmArgument "-XX:+AllowEnhancedClassRedefinition"
        }
    }
}

dependencies {
    jarJar(implementation("io.github.flemmli97:lingua_bib:${lingua_bib}-neoforge"))
}